In [ ]:
import pandas as pd
import numpy as np

# data = {
#     "name": ['Ali', 'Vali', 'Vali', 'Sami'],
#     "age": [25, np.nan, 30, np.nan],
#     "salary": [2000, 3000, np.nan, 4000]
# }

# df = pd.DataFrame(data)
# df.to_csv("data.csv", index=False)

# data = pd.read_csv("data.csv")
# # print(data['age'].isna().sum())

# data['age'] = data['age'].fillna(data['age'].mean())
# data['salary'] = data['salary'].fillna(data['salary'].median())
# # data = data.drop_duplicates(subset='name')
# old_count = len(data)
# new_count = len(data.drop_duplicates(subset='name'))
# print(old_count - new_count)

df = pd.DataFrame(
    {
        "age": [25, np.nan, 30, 22, 22],
        "salary": ["2000", "3000", "100000", "2500", "2500"]
    }
)
df.to_csv('df.csv', index=False)

data = pd.read_csv("df.csv")
data = data.drop_duplicates(subset=['age', 'salary'])
data['age'] = data['age'].fillna(data['age'].mean())
data['salary'] = data['salary'].astype(float)
data = data[data['salary'] <= 10000]
data

         age  salary
0  25.000000  2000.0
1  25.666667  3000.0
3  22.000000  2500.0

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {
        "name": [" Ali", "vali ", "SAMI", "Ali"],
        "salary": [2000, None, 3000, 2000]
    }
)

df.to_csv('advanced.csv', index=False)
data = pd.read_csv('advanced.csv')


data['name'] = data['name'].str.strip().str.lower()
data['salary'] = data['salary'].fillna(data['salary'].mean())
data = data.drop_duplicates(subset=['name', 'salary'])
data

   name       salary
0   ali  2000.000000
1  vali  2333.333333
2  sami  3000.000000