In [22]:
import pandas as pd
data = pd.read_csv('adult.data.csv')
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
# 1
data['sex'].value_counts()

sex
Male      6509
Female    3204
Name: count, dtype: int64

In [ ]:
# 2
print(data.loc[data['sex'] == 'Female']['age'].mean())

36.87546816479401

In [ ]:
# 3
germans = data.loc[data['native-country'] == 'Germany']
len(germans) * 100 / len(data)

0.442705652218676

In [12]:
# 4-5
more_than = data.loc[data['salary'] == '>50K']
less_than = data.loc[data['salary'] == '<=50K']
print(more_than['age'].mean())
print(more_than['age'].std())
print(less_than['age'].mean())
print(less_than['age'].std())

44.016912402428446
10.387259433171947
36.68863083985957
13.983012664508035

In [14]:
# 6
more_than = data.loc[data['salary'] == '>50K']
more_than['education'].unique()

array(['HS-grad', 'Masters', 'Bachelors', 'Some-college', 'Assoc-voc',
       'Doctorate', 'Prof-school', 'Assoc-acdm', '7th-8th', '12th',
       '10th', '11th', '9th', '5th-6th', '1st-4th'], dtype=object)

In [29]:
# 7
df = data.groupby(['age', 'sex'])
df.head()
df.describe()
data[data['race'] == 'Amer-Indian-Eskimo']['age'].max()

82

In [35]:
# 8
more_than = data.loc[data['salary'] == '>50K']

single = ['Never-married','Divorced','Separated','Widowed']
married = ['Married-civ-spouse','Married-spouse-absent','Married-AF-spouse']

single_count = more_than[more_than['marital-status'].isin(single)].shape[0]
married_count = more_than[more_than['marital-status'].isin(married)].shape[0]

print(single_count, married_count)

1105 6736

In [46]:
# 9
data['hours-per-week'].max()
len(data[data['hours-per-week'] == data['hours-per-week'].max()])
more_workers = data[data['hours-per-week'] == data['hours-per-week'].max()]
len(more_workers[more_workers['salary'] == '>50K']) * 100 / len(more_workers)

29.41176470588235

In [57]:
# 10
more_than.groupby('native-country')['hours-per-week'].mean()
less_than.groupby('native-country')['hours-per-week'].mean()

more_than[more_than['native-country'] == 'Japan']['hours-per-week'].mean()
less_than[less_than['native-country'] == 'Japan']['hours-per-week'].mean()

np.float64(41.857142857142854)